#!/bin/sh
set -eu
NAME=$1
MODEL=$2
LOGS=moe-analysis-logs-$NAME
mkdir "$LOGS"
<languages.txt \
    xargs -I{} \
    sbatch --job-name "{}" --output "$LOGS"/%x_slurm-%j.out noctua2_job "{}" "$NAME" "$MODEL"
