#!/bin/sh
#SBATCH -J "LOLA - MoE analysis"
#SBATCH -t 30:00
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem 10G
#SBATCH --gres=gpu:a100:1
#SBATCH --cpus-per-task=16

# Loading required modules
module load toolchain/foss/2022b
module load lib/libaio/0.3.113-GCCcore-12.2.0
module load lang
module load Anaconda3
module load system/CUDA/12.0.0
module load lib/NCCL/2.16.2-GCCcore-12.2.0-CUDA-12.0.0
module load compiler/GCC/10.3.0

export HF_HOME=/scratch/hpc-prf-lola/nikit/.cache/huggingface
CONDA_P=/scratch/hpc-prf-lola/nikit/repos/LOLA-Megatron-DeepSpeed/lola_ws/fine-tune/instruction-ft/venv-lola-ft

conda run --no-capture-output -p "$CONDA_P" ./moe_analysis.py --rows-limit 10000 --batch-size 1 --output-dir moe-noctua2-output --lang "$1"
